<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="surendrasinghgangwar" failures="1" tests="4" name="com.centralvista.test.RAMinistryMemberTest" time="31.876" errors="0" timestamp="2025-09-10T14:58:04 IST" skipped="0">
  <testcase classname="com.centralvista.test.RAMinistryMemberTest" name="rec_auth_minis_mem_requestverify" time="10.146"/>
  <testcase classname="com.centralvista.test.RAMinistryMemberTest" name="rec_auth_verifyMembervalues" time="0.556">
    <failure message="Date of Birth mismatch! Expected: 45828.0, Found: 20-06-2025" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Date of Birth mismatch! Expected: 45828.0, Found: 20-06-2025
at com.centralvista.test.RAMinistryMemberTest.validateField(RAMinistryMemberTest.java:215)
at com.centralvista.test.RAMinistryMemberTest.rec_auth_verifyMembervalues(RAMinistryMemberTest.java:189)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- rec_auth_verifyMembervalues -->
  <testcase classname="com.centralvista.test.RAMinistryMemberTest" name="minisMem_forwartoApprover" time="12.030"/>
  <testcase classname="com.centralvista.test.RAMinistryMemberTest" name="raminis_mem_logout" time="9.144"/>
</testsuite> <!-- com.centralvista.test.RAMinistryMemberTest -->
