<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="surendrasinghgangwar" failures="1" tests="11" name="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" time="177.640" errors="0" timestamp="2025-10-30T12:10:34 IST" skipped="0">
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="valid_registration" time="19.023"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_visitorrequest" time="12.892"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="visitor_admin_logout" time="9.138"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_verifyreq" time="15.564"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_fortoapprover" time="10.889"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="rec_authority_logout" time="14.129"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_verifyrequ" time="18.504"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_fortoissuer" time="22.720"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="app_authority_logout" time="14.113"/>
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="casualpass_verifyreqatIA" time="26.528">
    <failure message="No rows displayed after search for: Casual Pass expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No rows displayed after search for: Casual Pass expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.centralvista.test.VisitorAdmin.VisitorCasualPassTest.casualpass_verifyreqatIA(VisitorCasualPassTest.java:370)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- casualpass_verifyreqatIA -->
  <testcase classname="com.centralvista.test.VisitorAdmin.VisitorCasualPassTest" name="issuing_authority_logout" time="14.140"/>
</testsuite> <!-- com.centralvista.test.VisitorAdmin.VisitorCasualPassTest -->
